project:
  type: website
  output-dir: docs

# tell quarto to read the generated sidebar
metadata-files:
  - _sidebar.yml

quartodoc:
  out_index: _api_index.qmd
  # the name used to import the package you want to create reference docs for
  package: vidigi

  # write sidebar data to this file
  sidebar:
    file: "_sidebar.yml"
    style: docked
    search: true
    collapse-level: 2
    contents:
      - file: reference/index.qmd
        text: Reference
      - text: "Introduction"
        href: reference/introduction.qmd
      - section: "Examples"
        contents:
        - examples/example_1_simplest_case/ex_1_simplest_case.ipynb
        - examples/example_2_branching_multistep/ex_2_branching_multistep_case.ipynb
      - section: "Reference"
        contents:
          - function_reference.qmd
          - "{{ contents }}"

  sections:
    - title: All-In-One Animation Functions
      desc: ""
      contents:
        - animation.animate_activity_log
    - title: Step-By-Step Functions
      desc: ""
      contents:
        # the functions being documented in the package.
        # you can refer to anything: class methods, modules, etc..
        - prep.reshape_for_animations
        - prep.generate_animation_df
        - animation.generate_animation
    - title: Simpy Utility Functions and Classes
      desc: ""
      contents:
        - utils.populate_store
        - utils.CustomResource
    - title: ciw Utility Functions
      desc: ""
      contents:
        - utils.event_log_from_ciw_recs
